-- Human++ Neovim Colorscheme
-- Generated from palette.toml — DO NOT EDIT
-- Rebuild: make build

vim.cmd.highlight('clear')
vim.g.colors_name = 'humanplusplus'
vim.o.termguicolors = true

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ============================================================================
-- Editor UI
-- ============================================================================
hi('Normal',       { fg = '#dbd6cc', bg = '#1a1c22' })
hi('NormalFloat',  { fg = '#dbd6cc', bg = '#282b31' })
hi('FloatBorder',  { fg = '#5a5d62', bg = '#282b31' })
hi('FloatTitle',   { fg = '#f8f6f2', bg = '#282b31', bold = true })
hi('Cursor',       { fg = '#1a1c22', bg = '#f8f6f2' })
hi('CursorLine',   { bg = '#282b31' })
hi('CursorLineNr', { fg = '#f8f6f2', bg = '#282b31', bold = true })
hi('LineNr',       { fg = '#5a5d62' })
hi('Visual',       { bg = '#3a3d42' })
hi('VisualNOS',    { bg = '#3a3d42' })
hi('Search',       { fg = '#1a1c22', bg = '#f2a633' })
hi('IncSearch',    { fg = '#1a1c22', bg = '#f26c33' })
hi('CurSearch',    { fg = '#1a1c22', bg = '#f26c33' })
hi('Substitute',   { fg = '#1a1c22', bg = '#f26c33' })
hi('StatusLine',   { fg = '#f8f6f2', bg = '#282b31' })
hi('StatusLineNC', { fg = '#828079', bg = '#282b31' })
hi('TabLine',      { fg = '#828079', bg = '#282b31' })
hi('TabLineFill',  { bg = '#1a1c22' })
hi('TabLineSel',   { fg = '#f8f6f2', bg = '#1a1c22' })
hi('WinSeparator', { fg = '#3a3d42' })
hi('Pmenu',        { fg = '#dbd6cc', bg = '#282b31' })
hi('PmenuSel',     { fg = '#f8f6f2', bg = '#3a3d42' })
hi('PmenuSbar',    { bg = '#3a3d42' })
hi('PmenuThumb',   { bg = '#828079' })
hi('Folded',       { fg = '#828079', bg = '#282b31' })
hi('FoldColumn',   { fg = '#5a5d62', bg = '#1a1c22' })
hi('SignColumn',   { fg = '#5a5d62', bg = '#1a1c22' })
hi('ColorColumn',  { bg = '#282b31' })
hi('MatchParen',   { fg = '#f8f6f2', bg = '#3a3d42', bold = true })
hi('Directory',    { fg = '#458ae2' })
hi('Title',        { fg = '#f8f6f2', bold = true })
hi('ErrorMsg',     { fg = '#e7349c' })
hi('WarningMsg',   { fg = '#f26c33' })
hi('MoreMsg',      { fg = '#04b372' })
hi('Question',     { fg = '#04b372' })
hi('ModeMsg',      { fg = '#f8f6f2', bold = true })
hi('NonText',      { fg = '#3a3d42' })
hi('SpecialKey',   { fg = '#3a3d42' })
hi('Whitespace',   { fg = '#3a3d42' })
hi('Conceal',      { fg = '#828079' })
hi('SpellBad',     { undercurl = true, sp = '#e7349c' })
hi('SpellCap',     { undercurl = true, sp = '#f26c33' })
hi('SpellLocal',   { undercurl = true, sp = '#1ad0d6' })
hi('SpellRare',    { undercurl = true, sp = '#9871fe' })
hi('WildMenu',     { fg = '#1a1c22', bg = '#f2a633' })

-- ============================================================================
-- Diff
-- ============================================================================
hi('DiffAdd',    { bg = '#0e2919' })
hi('DiffChange', { bg = '#2b2311' })
hi('DiffDelete', { fg = '#e7349c', bg = '#2e1525' })
hi('DiffText',   { bg = '#3d3118' })
hi('Added',      { fg = '#61b186' })
hi('Changed',    { fg = '#f2a633' })
hi('Removed',    { fg = '#c8518f' })

-- ============================================================================
-- Syntax (quiet accents for code, loud reserved for signals)
-- ============================================================================
hi('Comment',     { fg = '#5a5d62', italic = true })
hi('String',      { fg = '#d2fc91' })
hi('Character',   { fg = '#d2fc91' })
hi('Number',      { fg = '#dfb683' })
hi('Float',       { fg = '#dfb683' })
hi('Boolean',     { fg = '#dfb683' })
hi('Constant',    { fg = '#dfb683' })
hi('Identifier',  { fg = '#f8f6f2' })
hi('Function',    { fg = '#5e84b6' })
hi('Statement',   { fg = '#c8518f' })
hi('Keyword',     { fg = '#c8518f' })
hi('Conditional', { fg = '#c8518f' })
hi('Repeat',      { fg = '#c8518f' })
hi('Operator',    { fg = '#828079' })
hi('Exception',   { fg = '#c8518f' })
hi('PreProc',     { fg = '#c8518f' })
hi('Include',     { fg = '#c8518f' })
hi('Define',      { fg = '#c8518f' })
hi('Macro',       { fg = '#d68c6f' })
hi('Type',        { fg = '#91cbcd' })
hi('StorageClass',{ fg = '#91cbcd', italic = true })
hi('Structure',   { fg = '#91cbcd' })
hi('Typedef',     { fg = '#91cbcd' })
hi('Special',     { fg = '#d68c6f' })
hi('SpecialChar', { fg = '#dfb683' })
hi('Tag',         { fg = '#c8518f' })
hi('Delimiter',   { fg = '#828079' })
hi('Debug',       { fg = '#e7349c' })
hi('Underlined',  { fg = '#458ae2', underline = true })
hi('Error',       { fg = '#e7349c' })
hi('Todo',        { fg = '#bbff00', bg = '#1a1c22', bold = true })

-- ============================================================================
-- Treesitter highlight groups (Neovim 0.9+)
-- ============================================================================
hi('@comment',               { link = 'Comment' })
hi('@string',                { link = 'String' })
hi('@string.escape',         { fg = '#dfb683' })
hi('@character',             { link = 'Character' })
hi('@number',                { link = 'Number' })
hi('@float',                 { link = 'Float' })
hi('@boolean',               { link = 'Boolean' })
hi('@constant',              { link = 'Constant' })
hi('@constant.builtin',      { fg = '#dfb683' })
hi('@variable',              { fg = '#f8f6f2' })
hi('@variable.parameter',    { fg = '#8f72e3', italic = true })
hi('@variable.builtin',      { fg = '#f8f6f2' })
hi('@variable.member',       { fg = '#f8f6f2' })
hi('@function',              { link = 'Function' })
hi('@function.call',         { fg = '#5e84b6' })
hi('@function.builtin',      { fg = '#5e84b6' })
hi('@function.method',       { fg = '#5e84b6' })
hi('@function.method.call',  { fg = '#5e84b6' })
hi('@keyword',               { link = 'Keyword' })
hi('@keyword.function',      { fg = '#c8518f' })
hi('@keyword.return',        { fg = '#c8518f' })
hi('@keyword.operator',      { fg = '#828079' })
hi('@keyword.import',        { fg = '#c8518f' })
hi('@keyword.storage',       { fg = '#91cbcd', italic = true })
hi('@type',                  { link = 'Type' })
hi('@type.builtin',          { fg = '#91cbcd' })
hi('@type.definition',       { fg = '#91cbcd' })
hi('@constructor',           { fg = '#91cbcd' })
hi('@operator',              { link = 'Operator' })
hi('@punctuation',           { fg = '#828079' })
hi('@punctuation.bracket',   { fg = '#828079' })
hi('@punctuation.delimiter', { fg = '#828079' })
hi('@punctuation.special',   { fg = '#d68c6f' })
hi('@tag',                   { fg = '#c8518f' })
hi('@tag.attribute',         { fg = '#91cbcd', italic = true })
hi('@tag.delimiter',         { fg = '#828079' })
hi('@attribute',             { fg = '#d68c6f' })
hi('@property',              { fg = '#f8f6f2' })
hi('@label',                 { fg = '#8f72e3' })
hi('@module',                { fg = '#91cbcd' })

-- Markup (markdown)
hi('@markup',                { fg = '#f8f6f2' })
hi('HppMarkdownNormal',     { fg = '#f8f6f2', bg = '#1a1c22' })
hi('@conceal.markdown_inline', { fg = '#828079' })
hi('@conceal.markdown',        { fg = '#828079' })
hi('@markup.heading',        { fg = '#f8f6f2', bold = true })
hi('@markup.heading.1',      { fg = '#1a1c22', bg = '#bbff00', bold = true })
hi('@markup.heading.2',      { fg = '#e7349c', bold = true })
hi('@markup.heading.3',      { fg = '#e7349c' })
hi('@markup.heading.4',      { fg = '#e7349c' })
hi('@markup.heading.5',      { fg = '#e7349c' })
hi('@markup.heading.6',      { fg = '#e7349c' })
hi('@markup.strong',         { fg = '#458ae2', bold = true })
hi('@markup.italic',         { fg = '#5e84b6', italic = true })
hi('@markup.raw',            { fg = '#f2a633' })
hi('@markup.raw.block',      { fg = '#91cbcd' })
hi('@markup.link',           { fg = '#d2fc91' })
hi('@markup.link.url',       { fg = '#5a5d62', underline = true })
hi('@markup.list',           { fg = '#828079' })
hi('@markup.quote',          { fg = '#91cbcd', italic = true })
hi('@markup.strikethrough',  { strikethrough = true })
hi('@punctuation.special.markdown', { fg = '#828079' })

-- Traditional vim markdown syntax groups (fallback for non-treesitter)
hi('markdownH1',                  { fg = '#1a1c22', bg = '#bbff00', bold = true })
hi('markdownH2',                  { fg = '#e7349c', bold = true })
hi('markdownH3',                  { fg = '#e7349c' })
hi('markdownH4',                  { fg = '#e7349c' })
hi('markdownH5',                  { fg = '#e7349c' })
hi('markdownH6',                  { fg = '#e7349c' })
hi('markdownHeadingDelimiter',    { fg = '#e7349c' })
hi('markdownBold',                { fg = '#458ae2', bold = true })
hi('markdownItalic',              { fg = '#5e84b6', italic = true })
hi('markdownBoldItalic',          { fg = '#458ae2', bold = true, italic = true })
hi('markdownCode',                { fg = '#f2a633' })
hi('markdownCodeBlock',           { fg = '#91cbcd' })
hi('markdownCodeDelimiter',       { fg = '#828079' })
hi('markdownLinkText',            { fg = '#d2fc91' })
hi('markdownUrl',                 { fg = '#5a5d62', underline = true })
hi('markdownListMarker',          { fg = '#828079' })
hi('markdownOrderedListMarker',   { fg = '#828079' })
hi('markdownBlockquote',          { fg = '#91cbcd', italic = true })
hi('markdownRule',                { fg = '#828079' })
hi('markdownStrikethrough',       { strikethrough = true })
hi('htmlH1',                      { fg = '#1a1c22', bg = '#bbff00', bold = true })
hi('htmlH2',                      { fg = '#e7349c', bold = true })
hi('htmlH3',                      { fg = '#e7349c' })
hi('htmlH4',                      { fg = '#e7349c' })
hi('htmlH5',                      { fg = '#e7349c' })
hi('htmlH6',                      { fg = '#e7349c' })
hi('htmlBold',                    { fg = '#458ae2', bold = true })
hi('htmlItalic',                  { fg = '#5e84b6', italic = true })
hi('mkdHeading',                  { fg = '#e7349c' })
hi('mkdCode',                     { fg = '#f2a633' })
hi('mkdCodeDelimiter',            { fg = '#828079' })
hi('mkdCodeStart',                { fg = '#828079' })
hi('mkdCodeEnd',                  { fg = '#828079' })
hi('mkdLink',                     { fg = '#d2fc91' })
hi('mkdURL',                      { fg = '#5a5d62', underline = true })
hi('mkdBlockquote',               { fg = '#91cbcd', italic = true })
hi('mkdListItem',                 { fg = '#828079' })
hi('mkdRule',                     { fg = '#828079' })

hi('@diff.plus',             { fg = '#61b186' })
hi('@diff.minus',            { fg = '#c8518f' })
hi('@diff.delta',            { fg = '#f2a633' })

-- ============================================================================
-- LSP Diagnostics
-- ============================================================================
hi('DiagnosticError',            { fg = '#e7349c' })
hi('DiagnosticWarn',             { fg = '#f26c33' })
hi('DiagnosticInfo',             { fg = '#1ad0d6' })
hi('DiagnosticHint',             { fg = '#5e84b6' })
hi('DiagnosticUnderlineError',   { undercurl = true, sp = '#e7349c' })
hi('DiagnosticUnderlineWarn',    { undercurl = true, sp = '#f26c33' })
hi('DiagnosticUnderlineInfo',    { undercurl = true, sp = '#1ad0d6' })
hi('DiagnosticUnderlineHint',    { undercurl = true, sp = '#5e84b6' })
hi('DiagnosticVirtualTextError', { fg = '#e7349c', bg = '#282b31' })
hi('DiagnosticVirtualTextWarn',  { fg = '#f26c33', bg = '#282b31' })
hi('DiagnosticVirtualTextInfo',  { fg = '#1ad0d6', bg = '#282b31' })
hi('DiagnosticVirtualTextHint',  { fg = '#5e84b6', bg = '#282b31' })
hi('DiagnosticSignError',        { fg = '#e7349c' })
hi('DiagnosticSignWarn',         { fg = '#f26c33' })
hi('DiagnosticSignInfo',         { fg = '#1ad0d6' })
hi('DiagnosticSignHint',         { fg = '#5e84b6' })

-- ============================================================================
-- Git signs (gitsigns.nvim etc.)
-- ============================================================================
hi('GitSignsAdd',    { fg = '#04b372' })
hi('GitSignsChange', { fg = '#f2a633' })
hi('GitSignsDelete', { fg = '#e7349c' })

-- ============================================================================
-- Telescope
-- ============================================================================
hi('TelescopeNormal',       { fg = '#dbd6cc', bg = '#1a1c22' })
hi('TelescopeBorder',       { fg = '#5a5d62', bg = '#1a1c22' })
hi('TelescopePromptNormal', { fg = '#f8f6f2', bg = '#282b31' })
hi('TelescopePromptBorder', { fg = '#282b31', bg = '#282b31' })
hi('TelescopePromptTitle',  { fg = '#1a1c22', bg = '#458ae2' })
hi('TelescopePreviewTitle', { fg = '#1a1c22', bg = '#04b372' })
hi('TelescopeResultsTitle', { fg = '#1a1c22', bg = '#1ad0d6' })
hi('TelescopeSelection',    { bg = '#282b31' })
hi('TelescopeMatching',     { fg = '#f2a633', bold = true })

-- ============================================================================
-- Human++ custom groups (used by the runtime plugin)
-- ============================================================================
hi('HppMarkerIntervention', { fg = '#1a1c22', bg = '#bbff00', bold = true })
hi('HppMarkerUncertainty',  { fg = '#f8f6f2', bg = '#9871fe', bold = true })
hi('HppMarkerDirective',    { fg = '#1a1c22', bg = '#1ad0d6', bold = true })
hi('HppDiagError',          { fg = '#1a1c22', bg = '#e7349c' })
hi('HppDiagWarn',           { fg = '#1a1c22', bg = '#f26c33' })
hi('HppDiagInfo',           { fg = '#1a1c22', bg = '#1ad0d6' })
hi('HppDiagHint',           { fg = '#f8f6f2', bg = '#5e84b6' })
hi('HppMarkdownH1',         { fg = '#1a1c22', bg = '#bbff00', bold = true })
hi('HppMarkdownH2',         { fg = '#e7349c', bold = true })
hi('HppMarkdownH3',         { fg = '#e7349c' })
hi('HppMarkdownH4',         { fg = '#e7349c' })
hi('HppMarkdownH5',         { fg = '#e7349c' })
hi('HppMarkdownH6',         { fg = '#e7349c' })
